services:
  postgres:
    image: postgres:latest
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER: eer0
      POSTGRES_PASSWORD: hahaha1234
      POSTGRES_DB: illusory-auth-service

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

#  grafana:
#    image: grafana/grafana-oss:latest
#    container_name: grafana
#    ports:
#      - '5005:3000'
#    volumes:
#      - grafana-data:/var/lib/grafana
#    restart: unless-stopped