version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5001:5432'
    environment:
      POSTGRES_USER: eer0
      POSTGRES_PASSWORD: hahaha1234
      POSTGRES_DB: illusory-auth-service